### ISSUE TITLE
Feature Request: Unit testing in RegAutomation 

### ISSUE THREAD

**Issue by haraldwer** [haraldwer/GDExtensionTemplate#12]
As the scope of the project grows, so does the potential for errors and issues. To tackle this, we could implement unit testing. 

Lets discuss unit testing and potential approaches. Before we start writing tests, lets define our feature / testing pipeline.

**Comment by haraldwer** [comment]
I have limited experience working with unit testing. As a gameplay programmer, most of my testing is by playing the game. This is not applicable in this context. 

I would like to let someone who is more experienced set this up.

**Comment by chocola-mint** [comment]
Here's a tentative task list to implement unit testing:
- [ ] Extract RegAutomation's "library" functions into a separate project under the same solution. (Maybe call it `RegAutomation.Core`)
  - It will take quite a bit of refactoring, but it makes perfect sense to separate the "frontend" (using the RegAutomation executable to preprocess C++ source files) and the "backend" (the actual functions that implement how to preprocess source files), and this refactoring will ultimately make things a lot more maintainable even without considering unit tests.
  - This is necessary because otherwise every test requires rebuilding the entire solution, which will cause the batch files to run scons and compile C++ source as well.
- [ ] Add a new C# class library project with the NUnit dependencies loaded. See [here](https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-nunit). This project will be called `RegAutomation.Core.Tests`.
- [ ] Implement tests for `RegAutomation.Core`.

**Comment by haraldwer** [comment]
Should we consider this done?

**Comment by chocola-mint** [comment]
Yeah, let's close it for now.
